language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - composer self-update
  - composer install -dev

script:
  - ./vendor/phpunit/phpunit/phpunit tests/
  - ./vendor/squizlabs/php_codesniffer/scripts/phpcs --standard=PSR1 --standard=PSR2 -np lib/
